# Generated by Django 4.0.2 on 2023-02-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdb',
            old_name='Name',
            new_name='User_Name',
        ),
    ]
